name: CI

on: [ push ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: npm Install
              working-directory: .
              run: |
                  npm install
            - name: npm Build
              working-directory: .
              run: |
                  CI=false npm run build
            - name: Deploy to S3
              uses: jakejarvis/s3-sync-action@master
              with:
                  args: --acl public-read --follow-symlinks --delete
              env:
                  AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET_NAME }}
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
                  AWS_REGION: ${{ secrets.AWS_REGION }}
                  SOURCE_DIR: "./build"
            - name: Invalidate CloudFront
              uses: chetan/invalidate-cloudfront-action@v2
              env:
                  DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
                  PATHS: "/*"
                  AWS_REGION: "us-east-1"
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}